[project]
name = "gibdd_bot_44"
version = "0.3.1"
requires-python = "==3.8.10"
dependencies = [
  "python-dotenv",
  "aiogram==3.*",
  "peewee",
]

[tool.black]
line-length = 79

[tool.ruff]
line-length = 79
